apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: t2micro-nodes
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20

