apiVersion: v1
kind: Pod
metadata:
  name: my-two-container
spec:
  nodeName: ip-192-168-58-71.ec2.internal
  containers:
  - name: my-container
    image: nginx
  - name: my-container-2
    image: busybox
    command: ["sleep", "3600"]  # keep busybox running

